version: '2'

services:
  database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "TCO18password"
        ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
  appsub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44399
    ports:
      - "8080:80"
      - "44399:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    build:
      context: .
      dockerfile: TestDocker01/Dockerfile
    depends_on:
      - database
#  test:
#    build: ./test-automation
#    depends_on: [appsub]
#    links:
#      - appsub
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./output:/output
#